import "server-only";
import type { RowDataPacket } from "mysql2";
import { db } from "@/lib/db";
import type { ClassroomOption, SubjectOption, SubjectRecord } from "@/components/admin/subjects/types";
import type { Classroom, ClassStudent, TeacherOption } from "@/components/admin/classes/types";

async function rows<T extends RowDataPacket>(sql: string) { const [result] = await db.execute<T[]>(sql); return result; }

export async function getAdminCounts() { const result=await rows<RowDataPacket&{students:number;teachers:number;subjects:number;attendanceToday:number}>(`SELECT (SELECT COUNT(*) FROM students) students,(SELECT COUNT(*) FROM teachers) teachers,(SELECT COUNT(*) FROM subjects) subjects,(SELECT COUNT(*) FROM attendance_records WHERE attendance_date=CURRENT_DATE AND status IN ('PRESENT','LATE')) attendanceToday`);return result[0]??{students:0,teachers:0,subjects:0,attendanceToday:0}; }
export async function getUsers(){return rows<RowDataPacket&{id:string;name:string;email:string;role:string;status:string}>(`SELECT CONCAT('A',id) id,full_name name,email,'Admin' role,status FROM admins UNION ALL SELECT CONCAT('T',id),full_name,email,'Teacher','ACTIVE' FROM teachers UNION ALL SELECT CONCAT('S',id),full_name,email,'Student','ACTIVE' FROM students ORDER BY role,name`)}
export async function getStudents(){return rows<RowDataPacket&{id:string;name:string;room:string;number:string;parent:string;phone:string}>(`SELECT s.student_code id,s.full_name name,COALESCE(c.name,'ยังไม่ระบุ') room,COALESCE(CAST(s.class_number AS CHAR),'-') number,COALESCE(s.parent_name,'-') parent,COALESCE(s.phone,'-') phone FROM students s LEFT JOIN classrooms c ON c.id=s.class_id ORDER BY s.student_code`)}
export async function getTeachers(){return rows<RowDataPacket&{id:string;name:string;department:string;subjects:string;phone:string}>(`SELECT COALESCE(t.teacher_code,CONCAT('T',LPAD(t.id,3,'0'))) id,t.full_name name,COALESCE(t.department,'-') department,COALESCE(GROUP_CONCAT(DISTINCT s.subject_name ORDER BY s.subject_name SEPARATOR ', '),'-') subjects,COALESCE(t.phone,'-') phone FROM teachers t LEFT JOIN subjects s ON s.teacher_id=t.id GROUP BY t.id ORDER BY t.full_name`)}
export async function getSubjects(){return rows<RowDataPacket&{id:string;name:string;teacher:string;room:string;students:string}>(`SELECT s.subject_code id,s.subject_name name,COALESCE(t.full_name,'ยังไม่กำหนด') teacher,COALESCE(c.name,'ยังไม่กำหนด') room,CONCAT((SELECT COUNT(*) FROM students st WHERE st.class_id=s.classroom_id),' คน') students FROM subjects s LEFT JOIN teachers t ON t.id=s.teacher_id LEFT JOIN classrooms c ON c.id=s.classroom_id ORDER BY s.subject_code`)}
export async function getSubjectPageData(){
  type SubjectRow=RowDataPacket&{databaseId:number;subjectCode:string;subjectName:string;teacherId:number|null;teacherName:string;gradeLevel:string|null;classId:number|null;className:string;semester:number;academicYear:string;credits:string;studyDays:string|null;startTime:string|null;endTime:string|null;location:string|null;attendanceMode:"EVERY_PERIOD"|"FIRST_PERIOD";isActive:number;description:string|null;studentCount:number};
  const subjectQuery=`SELECT s.id databaseId,s.subject_code subjectCode,s.subject_name subjectName,s.teacher_id teacherId,COALESCE(t.full_name,'ยังไม่กำหนด') teacherName,s.grade_level gradeLevel,s.classroom_id classId,COALESCE(c.name,'ยังไม่กำหนด') className,s.semester,s.academic_year academicYear,CAST(s.credits AS CHAR) credits,COALESCE(s.study_days,'') studyDays,IFNULL(TIME_FORMAT(s.start_time,'%H:%i'),'') startTime,IFNULL(TIME_FORMAT(s.end_time,'%H:%i'),'') endTime,COALESCE(s.location,'') location,s.attendance_mode attendanceMode,s.is_active isActive,COALESCE(s.description,'') description,(SELECT COUNT(*) FROM students st WHERE st.class_id=s.classroom_id) studentCount FROM subjects s LEFT JOIN teachers t ON t.id=s.teacher_id LEFT JOIN classrooms c ON c.id=s.classroom_id ORDER BY s.subject_code`;
  const legacySubjectQuery=`SELECT s.id databaseId,s.subject_code subjectCode,s.subject_name subjectName,s.teacher_id teacherId,COALESCE(t.full_name,'ยังไม่กำหนด') teacherName,c.level gradeLevel,s.classroom_id classId,COALESCE(c.name,'ยังไม่กำหนด') className,1 semester,'2569' academicYear,'1.0' credits,'' studyDays,'' startTime,'' endTime,'' location,'EVERY_PERIOD' attendanceMode,1 isActive,'' description,(SELECT COUNT(*) FROM students st WHERE st.class_id=s.classroom_id) studentCount FROM subjects s LEFT JOIN teachers t ON t.id=s.teacher_id LEFT JOIN classrooms c ON c.id=s.classroom_id ORDER BY s.subject_code`;
  let subjectPromise=rows<SubjectRow>(subjectQuery).catch((error:unknown)=>{if((error as {code?:string}).code==="ER_BAD_FIELD_ERROR")return rows<SubjectRow>(legacySubjectQuery);throw error});
  const [subjectRows,teacherRows,classRows,settingRows]=await Promise.all([
    subjectPromise,
    rows<RowDataPacket&SubjectOption>(`SELECT id,full_name name FROM teachers ORDER BY full_name`),
    rows<RowDataPacket&ClassroomOption>(`SELECT id,name,level FROM classrooms ORDER BY level,name`),
    rows<RowDataPacket&{academicYear:string}>(`SELECT academic_year academicYear FROM school_settings ORDER BY id LIMIT 1`),
  ]);
  const subjects:SubjectRecord[]=subjectRows.map(row=>({...row,semester:String(row.semester) as "1"|"2",gradeLevel:row.gradeLevel||classRows.find(c=>c.id===row.classId)?.level||"",studyDays:row.studyDays?row.studyDays.split(",").filter(Boolean):[],startTime:row.startTime||"",endTime:row.endTime||"",location:row.location||"",isActive:Boolean(row.isActive),description:row.description||""}));
  return {subjects,teachers:teacherRows,classrooms:classRows,academicYear:settingRows[0]?.academicYear||"2569"};
}
export async function getClasses(){return rows<RowDataPacket&{id:string;name:string;teacher:string;count:number}>(`SELECT CAST(c.id AS CHAR) id,c.name,COALESCE(t.full_name,'ยังไม่กำหนด') teacher,COUNT(s.id) count FROM classrooms c LEFT JOIN teachers t ON t.id=c.advisor_teacher_id LEFT JOIN students s ON s.class_id=c.id GROUP BY c.id,c.name,t.full_name ORDER BY c.name`)}
export async function getClassroomPageData(){
  const [classRows,studentRows,teacherRows,settingRows]=await Promise.all([
    rows<RowDataPacket&{id:number;name:string;level:string;advisorTeacherId:number|null;advisorName:string;studentCount:number}>(`SELECT c.id,c.name,c.level,c.advisor_teacher_id advisorTeacherId,COALESCE(t.full_name,'ยังไม่กำหนด') advisorName,COUNT(s.id) studentCount FROM classrooms c LEFT JOIN teachers t ON t.id=c.advisor_teacher_id LEFT JOIN students s ON s.class_id=c.id GROUP BY c.id,c.name,c.level,c.advisor_teacher_id,t.full_name ORDER BY c.level,c.name`),
    rows<RowDataPacket&{id:number;classId:number|null;number:number|null;code:string;name:string;faceRegistered:number}>(`SELECT s.id,s.class_id classId,s.class_number number,s.student_code code,s.full_name name,EXISTS(SELECT 1 FROM face_data f WHERE f.student_id=s.id AND f.status='READY') faceRegistered FROM students s ORDER BY s.class_number,s.student_code`),
    rows<RowDataPacket&TeacherOption>(`SELECT id,full_name name FROM teachers ORDER BY full_name`),
    rows<RowDataPacket&{academicYear:string;semester:number}>(`SELECT academic_year academicYear,semester FROM school_settings ORDER BY id LIMIT 1`),
  ]);
  const setting=settingRows[0]||{academicYear:"2569",semester:1};
  const classrooms:Classroom[]=classRows.map(c=>({...c,roomNumber:c.name.split("/").pop()||"",academicYear:setting.academicYear,semester:String(setting.semester) as "1"|"2",isActive:true,note:""}));
  const studentsByClass:Record<number,ClassStudent[]>={};
  for(const s of studentRows){if(!s.classId)continue;(studentsByClass[s.classId]??=[]).push({id:s.id,number:s.number||0,code:s.code,name:s.name,gender:s.name.includes("เด็กหญิง")||s.name.includes("นางสาว")?"หญิง":s.name.includes("เด็กชาย")||s.name.includes("นาย")?"ชาย":"ไม่ระบุ",status:"ปกติ",faceRegistered:Boolean(s.faceRegistered)})}
  return {classrooms,studentsByClass,teachers:teacherRows,academicYear:setting.academicYear,semester:String(setting.semester) as "1"|"2"};
}
export async function getFaces(){return rows<RowDataPacket&{id:string;name:string;photos:string;status:string;date:string}>(`SELECT s.student_code id,s.full_name name,CONCAT(f.image_count,' รูป') photos,CASE f.status WHEN 'READY' THEN 'พร้อมใช้งาน' WHEN 'NEEDS_IMAGES' THEN 'ควรเพิ่มรูป' ELSE 'ปิดใช้งาน' END status,DATE_FORMAT(f.registered_at,'%d/%m/%Y') date FROM face_data f JOIN students s ON s.id=f.student_id ORDER BY f.registered_at DESC`)}
export async function getAttendance(){return rows<RowDataPacket&{id:string;date:string;student:string;subject:string;time:string;status:string}>(`SELECT CAST(a.id AS CHAR) id,DATE_FORMAT(a.attendance_date,'%d/%m/%Y') date,st.full_name student,COALESCE(sb.subject_name,'-') subject,COALESCE(DATE_FORMAT(a.check_in_time,'%H:%i:%s'),'-') time,CASE a.status WHEN 'PRESENT' THEN 'มาเรียน' WHEN 'LATE' THEN 'สาย' WHEN 'ABSENT' THEN 'ขาด' ELSE 'ลา' END status FROM attendance_records a JOIN students st ON st.id=a.student_id LEFT JOIN subjects sb ON sb.id=a.subject_id ORDER BY a.attendance_date DESC,a.check_in_time DESC LIMIT 200`)}
