"use client";
import {useEffect,useRef,useState} from "react";import {Camera,CameraIcon,CheckCircle2,RefreshCw,SwitchCamera} from "lucide-react";
type ScanState="idle"|"ready"|"detecting"|"matching"|"success"|"error";
export default function FaceScanner(){const videoRef=useRef<HTMLVideoElement>(null),streamRef=useRef<MediaStream|null>(null);const [facing,setFacing]=useState<"user"|"environment">("user"),[state,setState]=useState<ScanState>("idle"),[message,setMessage]=useState("กดเปิดกล้องเพื่อเริ่มต้น");
 async function openCamera(mode=facing){streamRef.current?.getTracks().forEach(t=>t.stop());try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:mode,width:{ideal:1280},height:{ideal:720}},audio:false});streamRef.current=stream;if(videoRef.current)videoRef.current.srcObject=stream;setState("ready");setMessage("จัดใบหน้าให้อยู่กึ่งกลางกรอบ")}catch{setState("error");setMessage("ไม่สามารถเปิดกล้องได้ โปรดตรวจสอบสิทธิ์การใช้งานกล้อง")}}
 async function switchCamera(){const next=facing==="user"?"environment":"user";setFacing(next);await openCamera(next)}
 function scan(){if(state!=="ready")return;setState("detecting");setMessage("กำลังตรวจจับใบหน้า...");setTimeout(()=>{setState("matching");setMessage("กำลังเปรียบเทียบใบหน้า...");setTimeout(()=>{setState("success");setMessage("ยืนยันตัวตนสำเร็จ")},1500)},1400)}
 useEffect(()=>()=>streamRef.current?.getTracks().forEach(t=>t.stop()),[]);
 return <div className="scanner"><div className="camera-view"><video ref={videoRef} autoPlay muted playsInline/><div className="camera-shade"/><div className={`face-frame ${state}`}><span/><span/><span/><span/></div>{state==="idle"&&<div className="camera-empty"><CameraIcon size={46}/><p>กล้องยังไม่เปิด</p></div>}<div className={`scan-message ${state}`}>{state==="success"?<CheckCircle2 size={19}/>:<ScanFacePulse/>}{message}</div></div><div className="scanner-actions"><button className="button secondary" onClick={switchCamera} disabled={state==="idle"}><SwitchCamera size={18}/> สลับกล้อง</button><button className="button primary scan-start" onClick={state==="idle"?()=>openCamera():scan} disabled={state==="detecting"||state==="matching"||state==="success"}><Camera size={18}/>{state==="idle"?"เปิดกล้อง":"เริ่มสแกนใบหน้า"}</button><button className="button secondary" onClick={()=>openCamera()}><RefreshCw size={18}/> เปิดกล้องใหม่</button></div>{state==="success"&&<div className="scan-success"><CheckCircle2 size={27}/><div><h3>เช็คชื่อสำเร็จ</h3><p>การออกแบบเว็บไซต์ · 3 กันยายน 2569 · 12:56 น.</p></div><span>เข้าเรียน</span></div>}</div>}
function ScanFacePulse(){return <span className="pulse-dot"/>}
