CREATE TABLE IF NOT EXISTS admins (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  full_name VARCHAR(150) NOT NULL,
  password_hash VARCHAR(180) NOT NULL,
  status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE students ADD COLUMN IF NOT EXISTS class_id INT UNSIGNED NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS class_number INT UNSIGNED NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS phone VARCHAR(30) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS parent_name VARCHAR(150) NULL;
ALTER TABLE students ADD COLUMN IF NOT EXISTS status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS teacher_code VARCHAR(30) NULL;
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS department VARCHAR(100) NULL;
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS phone VARCHAR(30) NULL;
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE';

CREATE TABLE IF NOT EXISTS classrooms (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  level VARCHAR(30) NOT NULL,
  advisor_teacher_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_classroom_advisor (advisor_teacher_id)
);

CREATE TABLE IF NOT EXISTS subjects (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  subject_code VARCHAR(30) NOT NULL UNIQUE,
  subject_name VARCHAR(200) NOT NULL,
  teacher_id INT UNSIGNED NULL,
  classroom_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_subject_teacher (teacher_id),
  INDEX idx_subject_classroom (classroom_id)
);

ALTER TABLE subjects ADD COLUMN IF NOT EXISTS grade_level VARCHAR(10) NULL;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS semester TINYINT UNSIGNED NOT NULL DEFAULT 1;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS academic_year VARCHAR(10) NOT NULL DEFAULT '2569';
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS credits DECIMAL(3,1) NOT NULL DEFAULT 1.0;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS study_days VARCHAR(100) NULL;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS start_time TIME NULL;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS end_time TIME NULL;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS location VARCHAR(150) NULL;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS attendance_mode ENUM('EVERY_PERIOD','FIRST_PERIOD') NOT NULL DEFAULT 'EVERY_PERIOD';
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS description VARCHAR(255) NULL;

INSERT IGNORE INTO classrooms (name, level) VALUES
  ('ม.5/1', 'ม.5'),
  ('ม.5/2', 'ม.5'),
  ('ม.5/3', 'ม.5'),
  ('ม.5/4', 'ม.5');

CREATE TABLE IF NOT EXISTS face_data (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id INT UNSIGNED NOT NULL,
  reference_image_url VARCHAR(500) NULL,
  image_count INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('READY','NEEDS_IMAGES','INACTIVE') NOT NULL DEFAULT 'NEEDS_IMAGES',
  registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_face_student (student_id)
);

ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS room_number INT UNSIGNED NULL;
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS academic_year VARCHAR(10) NOT NULL DEFAULT '2569';
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS semester TINYINT UNSIGNED NOT NULL DEFAULT 1;
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS note VARCHAR(255) NULL;
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS face_samples (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id INT UNSIGNED NOT NULL,
  image_data MEDIUMBLOB NOT NULL,
  image_mime VARCHAR(50) NOT NULL,
  embedding JSON NOT NULL,
  quality_score DECIMAL(5,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_face_sample_student (student_id)
);

CREATE TABLE IF NOT EXISTS attendance_records (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  student_id INT UNSIGNED NOT NULL,
  subject_id INT UNSIGNED NULL,
  attendance_date DATE NOT NULL,
  check_in_time DATETIME NULL,
  status ENUM('PRESENT','LATE','ABSENT','LEAVE') NOT NULL,
  confidence DECIMAL(5,2) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_attendance_date (attendance_date),
  INDEX idx_attendance_student (student_id),
  UNIQUE KEY uq_attendance_student_subject_date (student_id, subject_id, attendance_date)
);

CREATE TABLE IF NOT EXISTS check_in_sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  subject_id INT UNSIGNED NOT NULL,
  classroom_id INT UNSIGNED NOT NULL,
  session_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  late_after TIME NOT NULL,
  status ENUM('ACTIVE','CLOSED') NOT NULL DEFAULT 'ACTIVE',
  created_by_admin_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_check_in_session_date (session_date),
  INDEX idx_check_in_session_subject (subject_id),
  UNIQUE KEY uq_check_in_session_round (subject_id, session_date, start_time)
);

ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS check_in_session_id BIGINT UNSIGNED NULL;

ALTER TABLE check_in_sessions MODIFY COLUMN created_by_admin_id INT UNSIGNED NULL;
ALTER TABLE check_in_sessions ADD COLUMN IF NOT EXISTS created_by_teacher_id INT UNSIGNED NULL;

CREATE TABLE IF NOT EXISTS audit_logs (
  log_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  action VARCHAR(50) NOT NULL,
  entity VARCHAR(50) NOT NULL,
  entity_id VARCHAR(50) NULL,
  description TEXT NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_user_created (user_id, created_at)
);

CREATE TABLE IF NOT EXISTS attendance_record_audits (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  attendance_record_id BIGINT UNSIGNED NOT NULL,
  admin_id INT UNSIGNED NOT NULL,
  action ENUM('ADD','STATUS_UPDATE') NOT NULL,
  old_status ENUM('PRESENT','LATE','ABSENT','LEAVE') NULL,
  new_status ENUM('PRESENT','LATE','ABSENT','LEAVE') NOT NULL,
  note VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_attendance_audit_record (attendance_record_id),
  INDEX idx_attendance_audit_admin (admin_id)
);

CREATE TABLE IF NOT EXISTS school_settings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  school_name VARCHAR(200) NOT NULL DEFAULT 'โรงเรียนขุขันธ์',
  academic_year VARCHAR(10) NOT NULL DEFAULT '2569',
  semester TINYINT UNSIGNED NOT NULL DEFAULT 1,
  school_start_time TIME NOT NULL DEFAULT '08:00:00',
  late_after TIME NOT NULL DEFAULT '08:15:00',
  face_recognition_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO school_settings (school_name)
SELECT 'โรงเรียนขุขันธ์'
WHERE NOT EXISTS (SELECT 1 FROM school_settings);
