ALTER TABLE face_data ADD COLUMN IF NOT EXISTS registered_by_id INT UNSIGNED NULL;
ALTER TABLE face_data ADD COLUMN IF NOT EXISTS registered_by_name VARCHAR(150) NULL;
ALTER TABLE face_data ADD COLUMN IF NOT EXISTS registered_by_role VARCHAR(50) NULL;
ALTER TABLE face_data ADD COLUMN IF NOT EXISTS device_type VARCHAR(50) NULL;
ALTER TABLE face_data ADD COLUMN IF NOT EXISTS device_name VARCHAR(150) NULL;
ALTER TABLE face_data ADD COLUMN IF NOT EXISTS browser VARCHAR(100) NULL;
ALTER TABLE face_data ADD COLUMN IF NOT EXISTS operating_system VARCHAR(100) NULL;
ALTER TABLE face_data ADD COLUMN IF NOT EXISTS camera_type VARCHAR(150) NULL;
ALTER TABLE face_samples ADD COLUMN IF NOT EXISTS pose_type VARCHAR(30) NULL;
